CREATE TABLE Type
(
id IDENTITY PRIMARY KEY,
name VARCHAR(50) NOT NULL
)

CREATE TABLE Hardware
(
id IDENTITY PRIMARY KEY,
naziv VARCHAR(50)    NOT NULL,
sifra VARCHAR(50)    NOT NULL,
cijena DOUBLE(10,2) NOT NULL,
typeId INT NOT NULL,
kolicina INT NOT NULL,
FOREING KEY(typeId) REFERENCES Type(id)


)